kind: pipeline
name: WireGuardX

clone:
  depth: 1
  
steps:
- name: assembleDebug
  image: archlinux:latest
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
    TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export TG_BOT_API"
    - "export GITHUB_TOKEN"
    - pacman -Sy make git gradle zip unzip wget patch ninja curl jdk8-openjdk jre8-openjdk cmake glibc --noconfirm
    - bash dronebuild