kind: pipeline
name: WireGuardX

clone:
  depth: 1
  
steps:
- name: assembleDebug
  image: alvrme/alpine-android-base:latest
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
    TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export TG_BOT_API"
    - "export GITHUB_TOKEN"
    - apk add bash cmake curl git make ninja patch
    - bash dronebuild