#!/bin/bash

ANDROID_SDK_VERSION=6609375
ANDROID_HOME="/opt/android-sdk"
mkdir -p ${ANDROID_HOME}/cmdline-tools
wget -q https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_VERSION}_latest.zip
unzip *tools*linux*.zip -d ${ANDROID_HOME}/cmdline-tools
rm *tools*linux*.zip
cp license_accepter.sh /opt/
chmod +x /opt/license_accepter.sh && /opt/license_accepter.sh ${ANDROID_HOME}

bash ${ANDROID_HOME}/cmdline-tools/tools/bin/sdkmanager --install "ndk;21.0.6113669"

DATE="`date +%d%m%Y-%H%M%S`"

HEAD_COMMIT="$(git rev-parse HEAD)"
GITHUB_URL="https://github.com/SensiPeeps/WireGuardX/commit/"
DRONE_URL="https://cloud.drone.io/SensiPeeps/WireGuardX/"

echo "sdk.dir=${ANDROID_HOME}" > local.properties

git clone https://github.com/WireGuard/wireguard-tools.git tunnel/tools/wireguard-tools/.

curl -s -X POST "https://api.telegram.org/bot${TG_BOT_API}/sendMessage" -d chat_id="-1001142276906" \
     -d "disable_web_page_preview=true" \
     -d "parse_mode=markdownV2" \
     -d text="⚒️ [*Building*](${DRONE_URL}${DRONE_BUILD_NUMBER}) with HEAD as [*$(echo $HEAD_COMMIT | cut -c1-8)*](${GITHUB_URL}${HEAD_COMMIT}) ⚒️"

git clone https://theradcolor:${GITHUB_TOKEN}@github.com/SensiPeeps/app_keystores -b master
mv app_keystores/sensipeeps_release.jks .
mv app_keystores/sp_wg_keystore.properties keystore.properties

./gradlew assembleRelease

if [ -f ui/build/outputs/apk/release/ui-release.apk ]; then
    cp ui/build/outputs/apk/release/ui-release.apk ui/build/outputs/apk/release/WireGuardX-${DATE}.apk
    cd ui/build/outputs/apk/release/
    APK=$(echo WireGuardX-*.apk)
    
    curl -F document=@"${APK}" "https://api.telegram.org/bot${TG_BOT_API}/sendDocument" \
         -F chat_id="-1001142276906"  \
         -F "disable_web_page_preview=true" \
         -F "parse_mode=html" \
         -F caption="⭕️ <b>CI build completed successfully!</b>"
    rm -rf ui/build/outputs/apk
else
    curl -s -X POST "https://api.telegram.org/bot${TG_BOT_API}/sendMessage" -d chat_id="-1001142276906" \
         -d "disable_web_page_preview=true" \
         -d "parse_mode=html" \
         -d text="❌ <b>Build error, exiting now!</b>"
fi
